version: '3'

services:
   webserv:
     build: .
     container_name: webserv_exp
     volumes:
       - "/Users/donghank/webserv_exp:/mnt/project"
     ports:
      - "80:80"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
      - "8086:8086"
      - "8087:8087"
      - "8088:8088"
      - "8089:8089"
      - "8090:8090"
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
     tty: true
