version: '3.8'

services:
   webserv:
     build: .
     container_name: webserv_exp
     volumes:
       - "path/to/your/project:/mnt/project"  # replace this with the path to your project (mount directly)
     ports:
      - "80:80"  # open the port that you want to use (here I use port 80)
     tty: true
